### ISSUE TITLE
LLVM can't compile the tests

### ISSUE THREAD

**Issue by Kim1230** [verificarlo/verificarlo#312]
Hello, 
I install LLVM and Clang
clang-10.0.1-1.ky10.x86_64
llvm-10.0.1-1.ky10.x86_64 
clang-tools-extra-10.0.1-1.ky10.x86_64
llvm-devel-10.0.1-1.ky10.x86_64
clang-devel-10.0.1-1.ky10.x86_64
![image](https://user-images.githubusercontent.com/107012598/191636427-93166c65-1af6-4dcb-9c4b-d79fd780ab80.png)
But when I installed the verificarlo and use `make installcheck` . It shows below:
![image](https://user-images.githubusercontent.com/107012598/191636237-74b21bf3-30ba-4d8a-a72f-4389e50ab77c.png)
and the reason for each test:
![image](https://user-images.githubusercontent.com/107012598/191636282-9a1f2448-08c7-4d42-9444-930c40fc4693.png)
It seems that LLVM can't compile the test. What I can do now? Hope for your help 
Thanks

**Comment by pablooliveira** [comment]
Hi @Kim1230. The error in the last log is `opt` complaining about the syntax of the generated IR files. In verificarlo, this can happen when the version of the `clang` binary used at compile time is different than the version of the `opt` binary. Sometimes this happens when you have another version of clang in the system, and a mixup happens during configure.

Could you check if that is the case ? You can look at the PATHS that are used by reading the header of the `verificarlo` script.

**Comment by Kim1230** [comment]
> Hi @Kim1230. The error in the last log is `opt` complaining about the syntax of the generated IR files. In verificarlo, this can happen when the version of the `clang` binary used at compile time is different than the version of the `opt` binary. Sometimes this happens when you have another version of clang in the system, and a mixup happens during configure.
> 
> Could you check if that is the case ? You can look at the PATHS that are used by reading the header of the `verificarlo` script.

Hello, Thanks for your reponse.  did you mean echo $PATH or something else? 
And I still install LLVM-15.0.0 and reconfigure verificarlo v0.8. It gets another problem:
![image](https://user-images.githubusercontent.com/107012598/191701130-7103b3a2-6f7b-41da-954a-a24b4fbe203f.png)

**Comment by pablooliveira** [comment]
>  did you mean echo $PATH or something else?
No, I meant looking at the tool paths that are defined in the beginning of the `verificarlo` script. You can get them with the following command:

``` head -n 50 `which verificarlo` ```

Could you please post the output of the previous command ?

**Comment by Kim1230** [comment]
Hello, this is the output:
![image](https://user-images.githubusercontent.com/107012598/191724863-82f6ce4e-ce90-460e-9e88-41f1e5a82e60.png)

**Comment by pablooliveira** [comment]
You are using the `clang` at `/usr/bin/clang` which I suspect is the default clang installed by your distribution. But the `opt` binary is taken at `/usr/local/bin/opt` which is a different version.

This might stem from a problem during configure. Please ensure that the clang and opt that are selected have the same version. You might want to put /usr/local/bin/ in your PATH during configure.

As a workaround you can also directly modify the file `which verificarlo` and replace clang and clang++ by the clang versions installed in /usr/local/bin/.

**Comment by Kim1230** [comment]
@pablooliveira  
Thanks a lot and it works!
but I got another problem 
[config.log](https://github.com/verificarlo/verificarlo/files/9625621/config.log)
And I don't know how to fix it?

**Comment by pablooliveira** [comment]
@Kim1230, the problem in the `config.log` triggers when we are checking that your installed clang 10.0 is working. Unfortunately, it seems the llvm you installed is not properly working and returns an error:

```
/usr/bin/ld: /tmp/cc6wbW4z.o:(.data.rel+0x0): undefined reference to `llvm::EnableABIBreakingChecks'
```

According to the post https://stackoverflow.com/questions/53805007/compilation-failing-on-enableabibreakingchecks, this seems to point to a mismatch between the installed runtime libraries and clang.

I think this has nothing to do with verificarlo but points to a problem with your LLVM installation (but might be wrong).

Maybe you could use instead the standard LLVM from your distribution which should be properly configured ?

**Comment by Kim1230** [comment]
@pablooliveira 
Thank you so much for your help. 
I reinstalled the LLVM from the source code. 
And the command is cmake -S llvm -B build -DCMAKE_INSTALL_PREFIX=/home/yjy/LLVM11.0/ -DLLVM_ENABLE_PROJECTS='clang' -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=On
it works!
And when I build : the command is ：
`./configure --prefix=/home/yjy/floatPrecision --without-flang CC=gcc CXX=g++`
but when I use  `make installcheck`
There are still some tests can't pass
![1663896512897](https://user-images.githubusercontent.com/107012598/191877862-2ee95e2a-00ba-4f7f-9259-0c98fa183099.png)
And when I see some errors ：
![image](https://user-images.githubusercontent.com/107012598/191877922-7433b4cf-4ccc-4709-8ba8-2f6a8bd1cdb6.png) for the test_absoluteError/
![image](https://user-images.githubusercontent.com/107012598/191877982-7af885d9-14b5-44fa-95a3-e0628b57881c.png) for the test_bitmask_backend/
![image](https://user-images.githubusercontent.com/107012598/191878089-269efd4f-ab26-4ef4-934a-8853630e4abc.png)
for /test_sparsity/
![image](https://user-images.githubusercontent.com/107012598/191878170-e1dbde49-6473-4f2c-aca5-38e94da3edcf.png)
for ../test_static_mode/
![image](https://user-images.githubusercontent.com/107012598/191878263-1afcb9be-1698-4b0d-84d3-825b06bce9fd.png)
for /test_unstable_branches
![image](https://user-images.githubusercontent.com/107012598/191878357-08fae202-e72b-48de-b553-d22c6b5dc6bc.png)
for test_vprec_instrument

And it is wired that the fortran tests are all passed.
Can you help me to solve the problem? Thanks a lot

**Comment by pablooliveira** [comment]
Dear @Kim1230, congrats on making progress. The remaining issues :
- `test_bitmask_backend`: this is a problem with Python parsing. I thought we had already fixed this issue, but it seems it is coming back. I will have a look at this, but you can safely ignore this failure. The problem is only in the test harness not in verificarlo.

- `test_unstable_branches` `test_static_mode` `test_absolute_error`: all these point to missing glib libraries and in particular libquadmath. Please ensure that the glib libraries installed match the glib used to compile gcc and g++ used. You might want to set during configure `CC=gcc CXX=g++` so they point to the default gcc/g++ compilers in your system.

Regarding fortran, to enable the tests you need to install flang-7.

Sorry about these issues, but when compiling verificarlo with non standard versions of the compilers, you have to be very careful because there are many dependencies ! I hope, this feedback helps solving your issues.

As a workaround you can always use the official Docker image which is properly configured.

**Comment by Kim1230** [comment]
@pablooliveira 
Thank you so much for your response. I have solved all the problems
