### ISSUE TITLE
MCA counter example

### ISSUE THREAD

**Issue by ddavid42** [verificarlo/verificarlo#346]
While conducting a benchmark, I encountered an interesting example where MCA, RR, and PB struggled to provide an accurate analysis (or at least made it challenging to demonstrate a complete loss of accuracy).

Here’s a straightforward example. I deliberately kept the value of N small, but even when increasing it to N=128, Verificarlo fails to deliver useful insights.
 
==============
```C
  #include <math.h>
  #include <stdio.h>
  #include <stdlib.h>
  
  double square_root(double x, int N){
      double res=x;
  
      for(int i=0; i<N; i++){
          res = sqrt(res);
      }
  
      return res;
  }
  
  double square(double x, int N){
      double res=x;
  
      for(int i=0; i<N; i++){
          res = res*res;
      }
  
      return res;
  }
  
  
  int main(int argc, char **argv){
      for(int N = 10; N<80; N+=10){
          for(double x=0.0; x<4.0; x+=0.5){
              double r = square_root(x, N);
              double s = square(r, N);
              printf("x=%f, N=%d, S=square_root(x,N)=%e, square(s,N)=%e\n", x, N, r, s);
          }
          printf("\n");
      }
      return 0;
  }
```

**Comment by pablooliveira** [comment]
Dear @ddavid42,

Thanks for the benchmark. Could you please explain clearly what is that you are missing ?

I tested your code with the `libinterflop_mca.so`. Ideally, I would do this with 30 samples at least, but just to demonstrate I take three MCA samples.

I compute the number of significant digits with $s ~ -\log(\sigma/|\mu|)$. Also ideally, one would apply a confidence interval, but here it is not necessary.

for N=60, x=4.0, I get the following three output samples 2.694926e+07, 1.638478e-28, 6.709994e+09
=> s ~ -0.34 < 0 (no significant digits at all, complete loss of significance)

for N=70, x=4.0, I get 0.000000e+00 inf and 0.000000e+00
=> s < 0 (no significant digits at all, complete loss of significance)

So, according to my brief tests, MCA does indeed report a total loss of significance here. 

If I did miss something, could you please explain what it is that you expect to see ?
If this answers your question, then please tell me so I can close this issue.

thanks !

**Comment by pablooliveira** [comment]
Dear @ddavid42,

Some clarifications : 
- Square root is not instrumented with MCA in any case. Currently, verificarlo does not instrument sqrt. (We can do it using libfuncinstrument + vprec backend, but not we do not define MCA for square roots).

- Indeed, MCA will not deterministically converge to 1.0. This is interesting, but not specific to this benchmark; there are different cases where MCA will not converge to the IEEE-754 computed value.

- MCA does though show a complete loss of accuracy.

Making this a conversation, since it is not an issue or a bug.

Thanks for the report.
